---
downloads: ~/.ansible-downloads/

configure_dotfiles: false
configure_terminal: false
configure_osx: false

configure_dock: true
dockitems_remove: 
  - Launchpad
  - TV
  - Podcasts
  - 'App Store'
  - News
  - Music
  - FaceTime
  - Reminders
  - Contacts
  - Calendar
  - Photos
  - Maps
  - Mail
  - Messages
  - Notes
  - Keynote
  - Numbers
  - Pages
  - App Store

dockitems_persist: 
- name: "VS Code"
  path: "/Applications/Visual Studio Code.app/"
  pos: 5

configure_sudoers: false
# sudoers_custom_config: ''
# Example:
# sudoers_custom_config: |
#   # Allow users in admin group to use sudo with no password.
#   %admin ALL=(ALL) NOPASSWD: ALL

# dotfiles_repo: https://github.com/geerlingguy/dotfiles.git
# dotfiles_repo_accept_hostkey: true
# dotfiles_repo_local_destination: ~/Development/GitHub/dotfiles
# dotfiles_files:
#   - .zshrc
#   - .gitignore
#   - .inputrc
#   - .osx
#   - .vimrc

homebrew_installed_packages:
  - dbmate
  - direnv
  - dnsperf
  - docker
  - docker-compose
  - iperf
  - jmeter
  - postgresql
  - sqlite
  - redis
  - go
  - iperf
  - nmap
  - wget
  - cmake
  - tldr
  - awscli
  - automake
  - terraform
  - gdb
  - ssh-copy-id
  - rust
  - rustup-init
  - openssh

homebrew_taps:
  - homebrew/core
  - homebrew/cask

homebrew_cask_appdir: /Applications

homebrew_cask_apps:
  - chromedriver
  - docker
  - medis
  - firefox
  - google-chrome
  - slack
  - sublime-text
  - visual-studio-code
  - dockutil
  - openvpn-connect
  - sublime-text
  - cheatsheet
  - notion

# See `geerlingguy.mas` role documentation for usage instructions.
mas_installed_apps: 
  - { id: 497799835, name: "Xcode" }
mas_email: ""
mas_password: ""

osx_script: "~/.osx --no-restart"

# Install packages from other package managers.
# Note: You are responsible for making sure the required package managers are
# installed, eg. through homebrew.
composer_packages: []
# - name: drush
#   state: present # present/absent, default: present
#   version: "^8.1" # default: N/A
gem_packages: []
# - name: bundler
#   state: present # present/absent/latest, default: present
#   version: "~> 1.15.1" # default: N/A
npm_packages: []
# - name: webpack
#   state: present # present/absent/latest, default: present
#   version: "^2.6" # default: N/A
pip_packages: []
# - name: mkdocs
#   state: present # present/absent/latest, default: present
#   version: "0.16.3" # default: N/A

# Set to 'true' to configure Sublime Text.
configure_sublime: false
# sublime_base_path: '~/Library/Application Support/Sublime Text'
# sublime_config_path: "Packages/User"
# sublime_package_control:
#   - "DocBlockr"
#   - "Dockerfile Syntax Highlighting"
#   - "FileDiffs"
#   - "GitHub Flavored Markdown Preview"
#   - "Jinja2"
#   - "Package Control"
#   - "PHP-Twig"
#   - "Pretty JSON"
#   - "SublimeLinter"
#   - "SublimeLinter-contrib-yamllint"
#   - "TrailingSpaces"
#   - "WordCount"

# Glob pattern to ansible task files to run after all other tasks are finished.
post_provision_tasks: []
